title: DnsCheck.Client
description: Unofficial .NET SDK for the DNS Check monitoring API
theme: jekyll-theme-minimal

url: https://markheydon.me.uk
baseurl: /dns-check-dotnet

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-seo-tag
  - jekyll-github-metadata

repository: markheydon/dns-check-dotnet

exclude:
  - contributing
